#!/bin/bash

# autorun from ~/.config/lxsession/LXDE-pi/autostart

APPS=/home/pi/saguaro-man/apps/
LOG=/logs/startup.log
NOW=$(date +"%y-%m-%d %H:%M:%S")

# Apps (directory names)
APP=video-recorder
#APP=another-app

STARTUP=$APPS$APP/startup
LOGFILE=$APPS$APP$LOG

# log
echo "$NOW|executing: $STARTUP" | tee -a $LOGFILE

# run app startup
#$STARTUP

# open terminal and run command for app startup
lxterminal -e $STARTUP
